
 

name: Setup Workspace
description: Action to setup NX Workspace
outputs:
  npm-dependencies-hit:
    description: Cache NPM dependencies found
    value: ${{ steps.npm-cache.outputs.cache-hit }}
runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version-file: '.nvmrc'
    
    - name: Cache NPM dependencies
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: npm-${{ hashFiles('package-lock.json') }}
        restore-keys: npm-
    
    - name: Install NPM dependencies
      shell: bash
      run: npm ci
    
    - name: Setup NX
      uses: nrwl/nx-set-shas@v3